### ISSUE TITLE
more data 

### ISSUE THREAD

**Issue by ismet00000** [spacenation/swiftui-grid#104]
How do more data, or how to control scroll.

**Comment by ay42** [comment]
Grid does not have a ScrollView. You can wrap it in to one like so
```swift
ScrollView {
    Grid { ... }
}
```
Do change data you just update the data itself and grid will redraw itself.

**Comment by ismet00000** [comment]
sorry for my bad english. 
Detecting that the person has seen the last data and asking for more from the server.
So how can the new item be brought down as it goes down. I tried a lot but I couldn't solve it.

**Comment by ay42** [comment]
Lazy loading is not possible at the moment.
