### ISSUE TITLE
Pull To Refresh Ideas?

### ISSUE THREAD

**Issue by StobyWan** [spacenation/swiftui-grid#38]
Lookin for a good way to pull down when the Grid is in top position to refresh.

**Comment by ay42** [comment]
@StobyWan I don't think there is a clean way to do this right now. However, it's possible to have a background view on a ScrollView and read position there to send to parent view with `preferences`.
You can then get those at a Grid level and add a `refresh` view.

**Comment by ay42** [comment]
@StobyWan with the release 1.0.0 grid is now a lower level ui element (like HStack) and ScrollView has been removed from it. This means that behaviours like `pull to refresh` and `lazy loading` have to be added at a ScrollView level. I'm closing this because it is now out of scope for this project.
