### ISSUE TITLE
Support for sections

### ISSUE THREAD

**Issue by TilBlechschmidt** [spacenation/swiftui-grid#7]
It'd be very useful to have the ability to split the content into sections with a header view each much like the sections in UICollectionView.

Probably the easiest way would be to add items into the VStack that take up the full width but that probably takes some refactoring of the `rowCount` method.

Right now I don't have much time at hand but if nobody picks this up I might work on a PR some time next week.

**Comment by ay42** [comment]
@TilBlechschmidt we just need to solve #10 and this will be possible.
With the latest release you can do the following but there will be a scroll view in each section:
```swift        
    VStack(alignment: .center) {
            Section(header: Text("Section 1")) {
                Grid {
                    ForEach(0...10, id: \.self) { _ in
                        Rectangle()
                            .foregroundColor(.random)
                            .frame(height: 20)
                    }
                }
            }
            
            Section(header: Text("Section 2")) {
                Grid {
                    ForEach(0...10, id: \.self) { _ in
                        Rectangle()
                            .foregroundColor(.random)
                            .frame(height: 20)
                    }
                }
            }
        }
```

**Comment by melgu** [comment]
Has #10 been solved already, as it's closed?

**Comment by ay42** [comment]
@melgu Sorry about the confusion. I meant this issue has a #10 as a dependency. #10 has been closed because I was not able to find a solution. Sections are not possible yet.

**Comment by ay42** [comment]
@melgu @TilBlechschmidt this is now possible with 1.0.0 and #80
