### ISSUE TITLE
NavigationLink's cell view not working inside grid

### ISSUE THREAD

**Issue by nobanhasan2** [spacenation/swiftui-grid#75]
Image and text rendered in the grid view
`   Grid(viewModel.items){ item in
                                        NavigationLink(destination: BookDetail(displayData: item)){
                                            SearchBookCell(displayData: item)
                                            }
                                       }
                                      .gridStyle(
                                        ModularGridStyle(columns: 2, rows: .fixed(200))
                                           ).animation(.easeInOut)`

**Comment by ay42** [comment]
@nobanhasan2 do you have a NavigationView one level above grid?
```swift
var body: some View {
    NavigationView {
        Grid(...)
    }
}

```

**Comment by ay42** [comment]
@nobanhasan2 I just added a working example with #79.
Closing this for now.

**Comment by nobanhasan2** [comment]
please see this screenshot 
https://drive.google.com/open?id=1WqTVLlI4AMMxioBADtkNLrH4K-At6-lY

**Comment by ay42** [comment]
@nobanhasan2 ok. I'm not sure what is now working for you there. Can you clarify.

**Comment by nobanhasan2** [comment]
Here is the full code. I don't know why its overlay on my image and also in text.
`    var body: some View {
        ZStack {
                    Color(0xedeef0)
                   .edgesIgnoringSafeArea(.all)
                   NavigationView{
                VStack {
                                      SearchBookBar(text: $viewModel.searchText)
                      //                List(viewModel.items) { item in
                      //
                      //                NavigationLink(destination: BookDetail(displayData: item)) {
                      //                    SearchBookCell(displayData: item)
                      //
                      //                }
                      //            }
                      //            .navigationBarTitle(Text("MeenaClick Search"))
                                      Grid(viewModel.items){ item in
                                        NavigationLink(destination: BookDetail(displayData: item)){
                                            SearchBookCell(displayData: item)
                                            }
                                       }
                                      .gridStyle(
                                        ModularGridStyle(columns: 2, rows: .fixed(200))
                                           ).animation(.easeInOut)
                     
                          
                              }
            }
            
               }`

**Comment by ay42** [comment]
@nobanhasan2 you mean where is the blue square should be an image rendered?

**Comment by ay42** [comment]
@nobanhasan2 my guess is you are missing this line.
https://github.com/spacenation/swiftui-grid/blob/978cc2eae7ced4a4d3cf9b6728503edc62a2969f/GridDemo%20iOS/StaggeredGrid/StaggeredGridView.swift#L14

**Comment by nobanhasan2** [comment]
@ay42 Yes.. i can solve the image render with that line but there Text is also rendered . Text has no function like renderingMode . How can i solve this?

**Comment by ay42** [comment]
@nobanhasan2 for text color change `.accentColor(...)`, `.foregroundColor(...)` ? Is that what you are trying to do just a color change?

**Comment by nobanhasan2** [comment]
i didn't do any color change. Everything was fine without NavigationLink

**Comment by ay42** [comment]
@nobanhasan2 navigation link makes it a button and it's rendered with system accent color

**Comment by nobanhasan2** [comment]
Ohhh now i see. Thank you so much bro for your help ^_^

**Comment by ay42** [comment]
@nobanhasan2 np
