### ISSUE TITLE
Bound preference GridPreferencesKey tried to update multiple times per frame.

### ISSUE THREAD

**Issue by ay42** [spacenation/swiftui-grid#81]
`Bound preference GridPreferencesKey tried to update multiple times per frame.` 
Debug message on grid init when grid is inside of ScrollView.

**Comment by adamdahan** [comment]
Getting the same issue

**Comment by badrinathvm** [comment]
How to fix this debug printing issue ?

**Comment by adamdahan** [comment]
@badrinathvm use apples new grid thats how you solve it :)

**Comment by badrinathvm** [comment]
Adopting LazyHGrid / LazyVGrid ?

**Comment by adamdahan** [comment]
@badrinathvm yeah at least this way if there are any issues the whole swift community will be working on a fix. It's no disrespect for this library. I thank them for making this. But apple seems to have solved the issue.

**Comment by sindresorhus** [comment]
There's no way AFAIK to do the staggered (waterfall) style grid with `LazyVGrid` though.

This library could definitely benefit from using `LazyVStack`.

**Comment by adamdahan** [comment]
@sindresorhus For now the best way achieve waterfall is UICollectionViewCompositionalLayout

**Comment by wingovers** [comment]
@sindresorhus @adamdahan Just use .indices or .ennumerated in the ForEach and develop a pattern by conditionally showing views based on the modulo across whatever multiples you want.
