### ISSUE TITLE
Layout by aspect ratio?

### ISSUE THREAD

**Issue by alexcurylo** [spacenation/swiftui-grid#82]
I want to autolayout a grid of squares where the width is calculated and the height is the same, ideally something that allowed for any aspect ratio like

 ```
    ModularGridStyle(columns: .min(135), rows: .aspectRatio(1))
```
That possible with the current `Tracks`? If not, what would you suggest as the best way to add it?

**Comment by ay42** [comment]
@alexcurylo unfortunately this is not possible at the moment. We will have to implement many more CSS Grid features to make this happen. We are moving in that direction but we are not there yet.
