### ISSUE TITLE
Don't work demo 

### ISSUE THREAD

**Issue by CPiersigilli** [spacenation/swiftui-grid#88]
Why do I get the error below when I try to use GridDemo.xcodeproj? I use Xcode 11.4.
<img width="1026" alt="Schermata 2020-03-28 alle 13 28 09" src="https://user-images.githubusercontent.com/17962752/77823001-0b2e3780-70f8-11ea-8ec8-ac225a8f37f7.png">

**Comment by ay42** [comment]
@CPiersigilli did you download this repo as a folder instead of cloning it?

**Comment by CPiersigilli** [comment]
I have download the repo from Github and I run `GridDemo.xcodeproj`
<img width="745" alt="Schermata 2020-03-28 alle 21 37 17" src="https://user-images.githubusercontent.com/17962752/77833272-5d914780-713c-11ea-9b95-59f239bdf0a7.png">

**Comment by ay42** [comment]
@CPiersigilli this is something I have to fix. Thank you for pointing this out.
For now you can make it work by renaming `swiftui-grid-master` to `swiftui-grid`

**Comment by CPiersigilli** [comment]
I download from Github your latest version `1.0.2` and works.
Don't work, in `GridDemo macOS`, only `Static Grid`: this is the result:
<img width="491" alt="image" src="https://user-images.githubusercontent.com/17962752/77842902-ec7f7d80-7197-11ea-87ca-fc16c26bd615.png">

**Comment by CPiersigilli** [comment]
Great. Now, with version 1.0.3, also `Static Grid` works in` GridDemo macOS`.
<img width="621" alt="image" src="https://user-images.githubusercontent.com/17962752/77843015-28ffa900-7199-11ea-9a1f-81ed3485d264.png">
