### ISSUE TITLE
In case the number of items is less than the number of tracks, the StaggeredGridStyle layout will collapse.

### ISSUE THREAD

**Issue by temoki** [spacenation/swiftui-grid#92]
I tried **GridDemo iOS**, the `StaggeredGridStyle` layout collapses in case the number of grid items is less than the number of tracks.

```swift
struct StaggeredGridView: View {
    @State var showSettings: Bool = false
    @State var style = StaggeredGridStyle(.vertical, tracks: .count(2), spacing: 1)
    @State var items: [Int] = (1...69).map { $0 }
```

These are screenshots of layout collapse.

- axis : .vertical
- tracks: .count(2)

| :+1: 3 items | 🤔 2 items |
| :-: | :-: |
| <img src="https://user-images.githubusercontent.com/3050100/77919911-bd245a00-72d8-11ea-8fbf-eec602385a7b.png" width="300" /> | <img src="https://user-images.githubusercontent.com/3050100/77919968-d1685700-72d8-11ea-86ed-ef22ef940b88.png" width="300" /> |

**Comment by temoki** [comment]
:smile:

**Comment by olivieratbliq** [comment]
I think that it is the same with the ModularGridStyle. If the number of items is smaller than the track count, the track size will be adjusted regardless of if there is an item to fill it. It seems that the track count calculation doesn't take into account the number of items in the grid. 
In other words, if you have two items in your grid and that you stretch the grid passed the size where a third could be added to the row, your two items will shrink to accommodate and empty space where the third item would be if you had one.

**Comment by pawankps** [comment]
Did someone get a quick fix?

**Comment by anoels** [comment]
Is there any progress for the abovementioned bug?
