### ISSUE TITLE
Gridview Layout collapses after opening the view for a second time.

### ISSUE THREAD

**Issue by anoels** [spacenation/swiftui-grid#96]
I just don't know if SDWebImageSwiftUI causes this issue.

```
Grid(self.store.state.myPostsState.posts) { index in
      RoundedURLImage(imageURL: postImageURL(uid: index.reference.documentID), borderWidth: 0)
    .scaledToFit()
     .cornerRadius(18)
      .clipped()
  }
   .animation(.easeInOut)
```

**Comment by anoels** [comment]
I just don't know if SDWebImageSwiftUI causes this issue. 

```
Grid(self.store.state.myPostsState.posts) { index in
                    RoundedURLImage(imageURL: postImageURL(uid: index.reference.documentID), borderWidth: 0)
                        .scaledToFit()
                        .cornerRadius(18)
                        .clipped()
                }
                .animation(.easeInOut)
```

**Comment by ay42** [comment]
@anoels it might if it's an async operation. Do you have the same error when using `SwiftUI.Image`?

**Comment by anoels** [comment]
It works fine with SwiftUI.Image. However, it seems like, this time, it also collapses if I add more view into the same Scrollview.

**Comment by denizaydemir** [comment]
In my case, this happens only if the grid has only 1 element to show.

**Comment by amrit42087** [comment]
It happens for me too. Whenever, I come to the view for the second time, the layout collapses.

**Comment by anoels** [comment]
It is because of the current version of the Swift that you are using. If you want, you can give it a try to the beta version of the XCode.
