### ISSUE TITLE
Scroll both vertically and horizontally same time

### ISSUE THREAD

**Issue by joshuazmiller** [spacenation/swiftui-grid#98]
How difficult would it be to make this library be able to scroll both vertically _and_ horizontally at _the same time_? I think this functionality would bring the library to another level at least for my application. Would this be overly difficult to accomplish? I would contribute to that if you think it seems doable/desirable feature @ay42

**Comment by ay42** [comment]
@joshuazmiller Let me try to add this example to the demo app. It might be possible without any modifications. I'll let you know how it goes.

**Comment by joshuazmiller** [comment]
Thank you @ay42 !

**Comment by ay42** [comment]
@joshuazmiller is the size of the scrollable content known before layout in your use case? or it grows dynamically in one direction?

**Comment by joshuazmiller** [comment]
@ay42 in my case it wouldn't grow based on user input, rather it's based on a list of items retrieved from a shared database
